
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: lambert_development

# test:
#   <<: *default
#   database: lambert_test
#   min_messages: warning
#
# acceptance:
#   <<: *default
#   database: lambert_acceptance
#   url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: lambert_production
#   url: <%= ENV['DATABASE_URL'] %>
